# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


# AWS_ACCESS_KEY_ID: "123"
# AWS_SECRET_ACCESS_KEY: "345"


development:
  SECRET_KEY_DEV: abc123
  GMAIL_USERNAME: example@example.com
  GMAIL_PASSWORD: password
  SENDGRID_USERNAME: username
  SENDGRID_PASSWORD: password
  S3_BUCKET: <YOUR_BUCKET>
  S3_ACCESS_KEY_ID: <YOUR_ACCESS_KEY_ID>
  S3_SECRET_ACCESS_KEY: <YOUR_SECRET_ACCESS_KEY>
  S3_REGION: <YOUR_REGION>
  SHRINE_SECRET_KEY_BASE: <YOUR SECRET KEY>


test:
  SECRET_KEY_TEST: abc123
  GMAIL_USERNAME: example@example.com
  GMAIL_PASSWORD: password
  SENDGRID_USERNAME: username
  SENDGRID_PASSWORD: password
  S3_BUCKET: <YOUR_BUCKET>
  S3_ACCESS_KEY_ID: <YOUR_ACCESS_KEY_ID>
  S3_SECRET_ACCESS_KEY: <YOUR_SECRET_ACCESS_KEY>
  S3_REGION: <YOUR_REGION>
  SHRINE_SECRET_KEY_BASE: <YOUR SECRET KEY>


production:
  SECRET_KEY_BASE: abc123
  GMAIL_USERNAME: example@example.com
  GMAIL_PASSWORD: password
  SENDGRID_USERNAME: username
  SENDGRID_PASSWORD: password
  S3_BUCKET: <YOUR_BUCKET>
  S3_ACCESS_KEY_ID: <YOUR_ACCESS_KEY_ID>
  S3_SECRET_ACCESS_KEY: <YOUR_SECRET_ACCESS_KEY>
  S3_REGION: <YOUR_REGION>
  SHRINE_SECRET_KEY_BASE: <YOUR SECRET KEY>

